trigger:
- pipeline-qa-master

variables:
  vmImage: 'agentPoolScaleSet1'  # Replace with your desired image
  # preInstallScript: |  # Script to run before build steps
  #   curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
  #   source ~/.bashrc

    # nvm install 20

stages:
- stage: Pipeline_QA
  displayName: Pipeline QA
  jobs:
  - job: Pipeline_QA
    displayName: Initialize
    pool:
      name: $(vmImage)
    variables:
    - group: PIPELINE_QA_DEV
    steps:
    - task: Bash@3
      displayName: 'Test dependency packages 1'
      inputs:
        targetType: 'inline'
        script: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
          source ~/.bashrc
          source /home/AzDevOps/.bashrc
          nvm -v


    

# - stage: Stage_Initialize_2
#   displayName: Stage Initialize
#   jobs:
#   - job: job_initialize_1
#     displayName: job initialize 1
#     pool:
#       name: 'agentPoolScaleSet1'
#     variables:
#     - group: PIPELINE_QA_DEV
#     steps:
#     - task: CmdLine@2
#       displayName: 'Test dependency packages 1'
#       inputs:
#         script: |
#           echo "Hello world 11"
#     - task: CmdLine@2
#       displayName: 'Test dependency packages 2'
#       inputs:
#         script: |
#           echo "Hello world 112"
          
#   - job: job_initialize_2
#     pool:
#       name: 'agentPoolScaleSet1'
#     variables:
#     - group: PIPELINE_QA_DEV
#     steps:
#     - task: CmdLine@2
#       displayName: 'Test dependency packages'
#       inputs:
#         script: |
#           echo "Hello world 2"