trigger:
- pipeline-qa-master

pool:
  vmImage: agentPoolScaleSet1

stages:
- stage: Stage_Initialize
  jobs:
  - job: job_initialize_1
    variables:
    - group: PIPELINE_QA_DEV
    steps:
    - task: CmdLine@2
      displayName: 'Test dependency packages'
      inputs:
        script: |
          echo "Hello world 1"
          
  - job: job_initialize_2
    variables:
    - group: PIPELINE_QA_DEV
    steps:
    - task: CmdLine@2
      displayName: 'Test dependency packages'
      inputs:
        script: |
          echo "Hello world 2"
